### ISSUE TITLE
About data set label format

### ISSUE THREAD

**Issue by wlc-git** [NeurAI-Lab/MMC#2]
'KAIST_COMBINed_COCO_train_set611 ': { "Data_dir" : "" train"," "Ann_file" : "train/sanitized_annotations/annotations/instances_comb json." " }, Which part of data is it? Is your JSON encapsulated XML or YOLO format? Are the train and test parts of KAIST data set used cleaned data Looking forward to your reply

**Comment by shruum** [comment]
Hi, thanks for your response.

The JSON is in XML COCO format. The original annotations included few errors and were also redundant, and hence we used a more sanitized set defines by [Multispectral Pedestrian Detection via Simultaneous Detection and Segmentation
](https://arxiv.org/abs/1808.04818)
