### ISSUE TITLE
How extract precision, recall and f1-score metrics

### ISSUE THREAD

**Issue by alancarlosml** [NeurAI-Lab/MMC#3]
Hello thank you for sharing the code.

I am using coco evaluator to mesuare the performance of my object detector. I would like to know if is possible to extract precision, recall and f1-score metrics. I already have the AP and AR metrics provided by coco.

Can you help me?

**Comment by shruum** [comment]
Hi, thanks for your question.
For these metrics, you have to enable the "precision_display" argument when calling test.py

`Ex. python test.py ... --precision_display --dataset_type <>`
