### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by kavya150801** [NeurAI-Lab/MMC#5]
I am working on this project and I am facing an issue while running both test and train files in anaconda prompt after installing all requirements except maskrCNN and nvidiadali 
error is : ModuleNotFoundError: No module named 'od'
also tried to run the file in google colab after mounting the whole od folder

**Comment by shruum** [comment]
Hi! Have you tried building the whole project with a conda environment name?
I am unable to reproduce this issue. Could you please provide more information? Thanks
